[tool.poetry]
name = "deep_learning"
version = "0.1.0"
description = ""
authors = ["Raoul Grouls <rgrouls@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.9,<=3.11.1"
loguru = "^0.7.0"
pandas = "^1.4.0"
matplotlib = "^3.5.1"
seaborn = "^0.11.2"
plotly = "^5.5.0"
scikit-learn = "^1.0.2"
pydantic = "^1.9.0"
tqdm = "^4.64.1"
torchvision = "*"
torch = "^2.0.1"
torchtext = "*"
torch-tb-profiler = "^0.4.0"
torchinfo = "^1.7.1"
torchsummary = "^1.5.1"
scipy = "^1.10.0"
mads-datasets = "^0.1"

[tool.poetry.group.tuning.dependencies]
gin-config = "^0.5.0"
ray = {extras = ["tune"], version = "^2.1.0"}
protobuf = "^3.20" # needed for ray
bayesian-optimization = "^1.4.2"
hpbandster = "^0.7.4"
configspace = "^0.6.0"
mlflow = "^2.1"

[tool.poetry.group.extras.dependencies]
shap = "^0.41"
hyperopt = "^0.2.7"

[tool.poetry.group.dev.dependencies]
black = "^23"
flake8 = "^6"
isort = "^5"
mypy = "^1.3"
pytest = "^7"
pep8-naming = "^0.12.1"
flake8-annotations = "^3.0.1"
jupyter = "^1.0.0"
nbformat = "^5.3.0"
importlib-resources = "^5.7.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
