[tool.poetry]
name = "deep_learning"
version = "0.1.0"
description = ""
authors = ["Raoul Grouls <raoul.grouls@businessdecision.nl>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
jax = {extras = ["cpu"], version = "^0.2.28"}
loguru = "^0.6.0"
plotly = "^5.5.0"
pandas = "^1.4.0"
nbformat = "^5.1.3"
scikit-learn = "^1.0.2"
seaborn = "^0.11.2"
torch = "^1.10.2"
torchvision = "^0.11.3"
trax = "^1.4.1"

[tool.poetry.dev-dependencies]
ipykernel = "^6.9.0"
black = "^22.1.0"
flake8 = "^4.0.1"
isort = "^5.10.1"
mypy = "^0.931"
pytest = "^7.0.0"
pep8-naming = "^0.12.1"
flake8-annotations = "^2.7.0"
hypothesis = "^6.36.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
