[tool.pdm.build]
includes = []

[project]
name = "mads-deeplearning"
version = "0.1.0"
description = ""

authors = [
    {name = "R.Grouls", email = "Raoul.Grouls@han.nl"},
]

requires-python = ">=3.10"
license = {text = "MIT"}

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Programming Language :: Python :: 3.10",
    "Typing :: Typed",
]

dependencies = [
    "torch>=2.0.1",
    "numpy>=1.25.0",
    "loguru>=0.7.0",
    "pydantic>=1.10.9",
    "pandas>=2.0.3",
    "mads-datasets>=0.1.5.4",
    "jupyter>=1.0.0",
    "matplotlib>=3.7.1",
    "seaborn>=0.12.2",
    "torchsummary>=1.5.1",
    "mltrainer>=0.1.4",
]

[tool.pdm.dev-dependencies]
lint = [
    "black>=23.3.0",
    "isort>=5.12.0",
    "mypy>=1.4.1",
    "pytest>=7.4.0",
    "ruff>=0.0.277",
]

[tool.flake8]
ignore = ["W503", "ANN101", "ANN002", "ANN003"]
max-line-length = 88
max-complexity = 18
exclude = ["__init__.py", "tests/*", "docs/*", "examples/*", "scripts/*"]
select = "C,E,F,W,B,B950"
extend-ignore = "E203, E501"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
use_parentheses = true
line_length = 88

[tool.mypy]
ignore_missing_imports = true
strict_optional = true
warn_unreachable = true
pretty = true